### ISSUE TITLE
Please read the details

### ISSUE THREAD

**Issue by SpiffGreen** [midnqp/frameworkless#4]
![code](https://user-images.githubusercontent.com/73044138/121459674-9c0ecd00-c9a3-11eb-816c-07151d715e07.png)
![code1](https://user-images.githubusercontent.com/73044138/121459694-a335db00-c9a3-11eb-96a6-051108bb4aa6.png)

Hi Sir, I looked through your code on **frameworkless** and discovered few problems which I was able to solve but I clearly changed everything though(I’m not very good at understanding other people’s code very quickly, so I wrote my version since I understand the idea). What I did:
- It works fine with more than one node script in HTML
- I made a simple function for including components though it's still under development as I intend to allow the passing of component state as a second parameter to include function(optional).
- It generates HTML safely without exposing the server-side code.
- It handles routing intelligently, as HTML extension can be excluded.
- Using return statement works as each nodejs script is actually a function
- Each of these functions has access to a function called include for including components, require, request and response.
All I have done is available on [ServeJS](https://github.com/SpiffGreen/ServeJS)

**Comment by midnqp** [comment]
In `inlcude </components/navbar>`, if navbar.html also had `<script nodejs>`, will it get rendered?

**Comment by SpiffGreen** [comment]
In my implementation of frameworkless I only returned a modified content of the component as template values are replaced with their appropriate values. No nodejs script is executed until everything is included in the main script.

**Comment by midnqp** [comment]
## My question rephrased again.

For example, let's say, you're responding to 
`/contact` by `contact.html`, and contact.html includ es `navbar.html`. And navbar.html has `<script nodejs>`. 

The question is: will that `<script nodejs>` inside navbar.html work?

**Comment by midnqp** [comment]
> ## My question rephrased again.
> For example, let's say, you're responding to
> `/contact` by `contact.html`, and contact.html includ es `navbar.html`. And navbar.html has `<script nodejs>`.
> 
> The question is: will that `<script nodejs>` inside navbar.html work?

@SpiffGreen If that doesn't work, we just lost the whole purpose for this framework.

**Comment by SpiffGreen** [comment]
It didn't work. I just modified the code to make it work
